---
name: "build"

on: push

jobs:
  build-resume:
    name: "Build resume"
    runs-on: "ubuntu-22.04"  # https://github.com/puppeteer/puppeteer/issues/12818
    strategy:
      matrix:
        position:
          - "Systems Administrator"
          - "DevOps Engineer"
          - "Full-stack Engineer"
    steps:
      - name: "checkout resume-generator"
        uses: "actions/checkout@v4"
        with:
          repository: "guppy0130/resume-generator"
      - name: "checkout self"
        uses: "actions/checkout@v4"
        with:
          path: "resume-data"
      - uses: "oven-sh/setup-bun@v2"
        with:
          bun-version: "latest"
      - run: "bun install"
      - name: "fetch pfp"
        run: "curl -fsSL https://github.com/guppy0130.png -o resume-data/img.jpg"
      - name: "build resume for ${{ matrix.position }}"
        run: |-
          bun run index.ts \
            -d resume-data \
            -t templates/guppy0130 \
            -o "resume-${{ matrix.position }}.pdf" \
            -p "${{ matrix.position }}"
      - name: "Upload artifacts"
        uses: "actions/upload-artifact@v4"
        with:
          name: "resume-${{ matrix.position }}"
          if-no-files-found: "error"
          path: |
            *.pdf

  release-resume:
    needs:
      - "build-resume"
    permissions:
      id-token: write
      attestations: write
    name: "release resume"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/download-artifact@v4"
      - uses: "actions/attest-build-provenance@v2"
        with:
          subject-path: "*.pdf"
      - name: "release"
        uses: "softprops/action-gh-release@v2"
        with:
          draft: true
          files: |
            *.pdf
